use_frameworks!

platform :ios, '9.0'

target 'lssbb_Example' do
  pod 'lssbb', :path => '../'

  target 'lssbb_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
